name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: test-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: testdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    name: Deploy

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.5
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      # Installs the Node version specified in package.json
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: package.json

      # Installs the NPM version specified in package.json
      - name: Install npm
        run: npm install -g npm@$(node -p "require('./package.json').engines.npm.replace('>=', '')")

      - name: Copy environment file
        run: cp .env.github .env

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Composer audit
        run: composer audit

      - name: Generate app key
        run: php artisan key:generate

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Tests
        run: ./vendor/bin/pest --ci --parallel

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure()
        with:
          path: |
            storage/logs
            tests/Browser/Screenshots
          retention-days: 3

#      - name: Notify LogSnag
#        if: always()
#        run: |
#          if [ "${{ job.status }}" = "success" ]; then
#            EVENT="CI succeeded"
#            ICON="✅"
#            NOTIFY=false
#          else
#            EVENT="CI failed"
#            ICON="❌"
#            NOTIFY=true
#          fi
#
#          curl --location --request POST 'https://api.logsnag.com/v1/log' \
#          --header "Authorization: Bearer ${{ secrets.LOGSNAG_API_KEY }}" \
#          --header "Content-Type: application/json" \
#          --data-raw "{
#              \"project\": \"hosmic\",
#              \"channel\": \"deployments\",
#              \"event\": \"$EVENT\",
#              \"icon\": \"$ICON\",
#              \"notify\": $NOTIFY
#          }"

#      - name: Deploy to server
#        if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: curl --fail-with-body -X POST "${{ secrets.FORGE_DEPLOY_URL }}"